# required
# count: 1
apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  name: {{ .metadata.name }}
spec:
  {{- if hasKey .spec "repositoryDigestMirrors" }}
  repositoryDigestMirrors:
    {{- .spec.repositoryDigestMirrors | toYaml | nindent 4 }}
  {{- end }}
