---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hub-config
  namespace: openshift-gitops
spec:
  destination: 
    server: "https://kubernetes.default.svc"
    namespace: default
  project: infra
  syncPolicy:
    automated:
      allowEmpty: true
      selfHeal: true
      prune: true
  syncOptions:
  - CreateNamespace=true
  - ServerSideApply=true
  - Validate=false
  source:
    path: telco-hub/configuration/reference-crs
    repoURL: 'https://github.com/openshift-kni/telco-reference.git'
    targetRevision: main
