apiVersion: v1
kind: Secret
metadata:
  name: ztp-repo
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://gitlab.example.com/namespace/repo
  password: password
  username: username
  insecure: "false" # Set to true if using an internal registry with an internally signed SSL certificate
  forceHttpBasicAuth: "true"
