apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: load-sctp-module
  labels:
    machineconfiguration.openshift.io/role: {{ index (or .metadata.labels dict)  "machineconfiguration.openshift.io/role" }}
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
        - contents:
            source: data:,
          mode: 420
          overwrite: true
          path: /etc/modprobe.d/sctp-blacklist.conf
        - contents:
            {{- $sctpData := "" }}
            {{- range $file := (or .spec.config.storage.files list) }}
              {{- if eq $file.path "/etc/modules-load.d/sctp-load.conf" }}
                {{- $sctpData = $file.contents.source }}
                {{- if not (eq $sctpData "data:,sctp" "data:text/plain;charset=utf-8,sctp" "data:text/plain;charset=utf-8;base64,c2N0cA==") }}
                  {{- $sctpData = "data:,sctp (or equivalent encoded values)" }}
                {{- end }}
              {{- end }}
            {{- end }}
            source: {{ $sctpData }}
          mode: 420
          overwrite: true
          path: /etc/modules-load.d/sctp-load.conf
