---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
    name: group-du-standard-pgt
placementBindingDefaults:
    name: group-du-standard-pgt-placement-binding
policyDefaults:
    namespace: ztp-group
    placement:
        labelSelector:
            matchExpressions:
                - key: group-du-standard-zone
                  operator: In
                  values:
                    - zone-1
                - key: hardware-type
                  operator: In
                  values:
                    - hw-type-platform-1
    remediationAction: inform
    severity: low
    namespaceSelector:
        exclude:
            - kube-*
        include:
            - '*'
    evaluationInterval:
        compliant: 10m
        noncompliant: 10s
policies:
    - name: group-du-standard-pgt-group-du-standard-cfg-pc
      policyAnnotations:
        ran.openshift.io/ztp-deploy-wave: ""
      manifests:
        - path: source-crs/PtpOperatorConfig-MCP-worker.yaml
        - path: source-crs/PtpConfigSlave-MCP-worker.yaml
          patches:
            - metadata:
                name: du-ptp-slave
              spec:
                profile:
                    - interface: '{{hub fromConfigMap "" "group-hardware-types-configmap" (printf "%s-ptpcfgslave-profile-interface" (index .ManagedClusterLabels "hardware-type")) hub}}'
                      name: slave
                      phc2sysOpts: -a -r -n 24
                      ptp4lOpts: -2 -s --summary_interval -4
          openapi:
            path: schema.openapi
        - path: source-crs/SriovOperatorConfig-MCP-worker.yaml
        - path: source-crs/PerformanceProfile-MCP-worker.yaml
          patches:
            - spec:
                cpu:
                    isolated: '{{hub fromConfigMap "" "group-hardware-types-configmap" (printf "%s-cpu-isolated" (index .ManagedClusterLabels "hardware-type")) hub}}'
                    reserved: '{{hub fromConfigMap "" "group-hardware-types-configmap"  (printf "%s-cpu-reserved" (index .ManagedClusterLabels "hardware-type")) hub}}'
                hugepages:
                    defaultHugepagesSize: '{{hub fromConfigMap "" "group-hardware-types-configmap" (printf "%s-hugepages-default" (index .ManagedClusterLabels "hardware-type")) hub}}'
                    pages:
                        - count: '{{hub fromConfigMap "" "group-hardware-types-configmap" (printf "%s-hugepages-count" (index .ManagedClusterLabels "hardware-type")) | toInt hub}}'
                          size: '{{hub fromConfigMap "" "group-hardware-types-configmap" (printf "%s-hugepages-size" (index .ManagedClusterLabels "hardware-type")) hub}}'
        - path: source-crs/TunedPerformancePatch-MCP-worker.yaml
        - path: source-crs/optional-extra-manifest/enable-crun-master.yaml
        - path: source-crs/optional-extra-manifest/enable-crun-worker.yaml
