apiVersion: agent-install.openshift.io/v1beta1
kind: AgentServiceConfig
metadata:
  name: agent
spec:
  osImages:
  - openshiftVersion: "4.17"
  - openshiftVersion: "4.16"
  - openshiftVersion: "4.15"


    
