---
apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
  annotations:
    argocd.argoproj.io/sync-wave: "12"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  namespace: open-cluster-management-observability
type: Opaque
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket:  "<BUCKET_NAME>"
      endpoint: "<BUCKET_HOST>"
      insecure: true
      access_key: "<AWS_ACCESS_KEY_ID>"
      secret_key: "<AWS_SECRET_ACCESS_KEY>"
