---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
    name: group-du-sno-latest
placementBindingDefaults:
    name: group-du-sno-latest-placement-binding
policyDefaults:
    namespace: ztp-group
    placement:
        labelSelector:
            matchExpressions:
                - key: du-profile
                  operator: In
                  values:
                    - latest
                - key: group-du-sno
                  operator: Exists
    remediationAction: inform
    severity: low
    namespaceSelector:
        exclude:
            - kube-*
        include:
            - '*'
    evaluationInterval:
        compliant: 10m
        noncompliant: 10s
policies:
    - name: group-du-sno-latest-config-policy
      policyAnnotations:
        ran.openshift.io/ztp-deploy-wave: ""
      manifests:
        - path: source-crs/DisableOLMPprof.yaml
        - path: source-crs/ClusterLogForwarder.yaml
          patches:
            - spec:
                filters:
                    - name: ran-du-labels
                      openshiftLabels:
                        label1: test1
                        label2: test2
                        label3: test3
                        label4: test4
                outputs:
                    - kafka:
                        url: tcp://10.46.55.190:9092/test
                      name: kafka-output
          openapi:
            path: schema.openapi
        - path: source-crs/PtpConfigSlave-MCP-master.yaml
          patches:
            - metadata:
                name: du-ptp-slave
              spec:
                profile:
                    - interface: ens5f0
                      name: slave
                      phc2sysOpts: -a -r -n 24
                      ptp4lOpts: -2 -s --summary_interval -4
          openapi:
            path: schema.openapi
        - path: source-crs/SriovOperatorConfigForSNO-MCP-master.yaml
          patches:
            - spec:
                configDaemonNodeSelector:
                    node-role.kubernetes.io/worker: ""
        - path: source-crs/StorageLV.yaml
          patches:
            - spec:
                storageClassDevices:
                    - devicePaths:
                        - /dev/disk/by-path/pci-0000:88:00.0-nvme-1
                      fsType: xfs
                      storageClassName: example-storage-class-1
                      volumeMode: Filesystem
                    - devicePaths:
                        - /dev/disk/by-path/pci-0000:89:00.0-nvme-1
                      fsType: xfs
                      storageClassName: example-storage-class-2
                      volumeMode: Filesystem
        - path: source-crs/DisableSnoNetworkDiag.yaml
        - path: source-crs/PerformanceProfile-MCP-master.yaml
          patches:
            - spec:
                cpu:
                    isolated: 2-31,34-63
                    reserved: 0-1,52-53
                hugepages:
                    defaultHugepagesSize: 1G
                    pages:
                        - count: 32
                          size: 1G
        - path: source-crs/TunedPerformancePatch-MCP-master.yaml
        - path: source-crs/optional-extra-manifest/enable-crun-master.yaml
        - path: source-crs/optional-extra-manifest/enable-crun-worker.yaml
