generators:
- acm-common-ranGen.yaml
- acm-group-du-sno-ranGen.yaml
- acm-group-du-sno-validator-ranGen.yaml
- acm-group-du-3node-ranGen.yaml
- acm-group-du-3node-validator-ranGen.yaml
- acm-group-du-standard-ranGen.yaml
- acm-group-du-standard-validator-ranGen.yaml
- acm-example-sno-site.yaml
- acm-example-multinode-site.yaml
resources:
- ns.yaml
- hub-side-templating/configMaps/group-hardware-types-configmap.yaml
- hub-side-templating/configMaps/group-zones-configmap.yaml
- hub-side-templating/configMaps/site-data-configmap.yaml
- group-du-clo5-cleanup-policy.yaml
