apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placementrule-group-du-sno-clo5-cleanup
  namespace: ztp-group
spec:
  clusterSelector:
    matchExpressions:
    - key: group-du-sno
      operator: Exists
    - key: du-profile
      operator: In
      values:
      - latest
    - key: clo5-cleanup-done
      operator: DoesNotExist
