apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-group-du-sno-validator-latest-du-policy
  namespace: ztp-group
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        - key: du-profile
          operator: In
          values:
          - latest
        - key: group-du-sno
          operator: Exists
        - key: ztp-done
          operator: DoesNotExist
  tolerations:
  - key: cluster.open-cluster-management.io/unavailable
    operator: Exists
  - key: cluster.open-cluster-management.io/unreachable
    operator: Exists
