---
apiVersion: v1beta1
kind: AgentConfig
metadata:
  name: hub  # need to match the same name put in install-config
rendezvousIP: 192.168.125.20  # one of the master IP
hosts:
  - hostname: hub-ctl-0
    role: master
    interfaces:
      - macAddress: aa:aa:aa:aa:01:01
    rootDeviceHints:
      deviceName: "/dev/disk/by-path/pci-0000:00:07.0"
  - hostname: hub-ctl-1
    role: master
    interfaces:
      - macAddress: aa:aa:aa:aa:01:02
    rootDeviceHints:
      deviceName: "/dev/disk/by-path/pci-0000:00:07.0"
  - hostname: hub-ctl-2
    role: master
    interfaces:
      - macAddress: aa:aa:aa:aa:01:03
    rootDeviceHints:
      deviceName: "/dev/disk/by-path/pci-0000:00:07.0"
